#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    pos_ratio = 0
    neg_ratio = 0
    zero_ratio = 0
    
    for num in arr:
        if num > 0:
            pos_ratio += 1
        elif num < 0:
            neg_ratio += 1
        else:
            zero_ratio += 1
    
    print(pos_ratio/len(arr))
    print(neg_ratio/len(arr))
    print(zero_ratio/len(arr))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
